[FIX] fieldservice_account_analytic: add demo data for tests
This fixes unit tests in other modules like `fieldservice_sale`, which don't
directly depend on this one.

e.g.:
```
  File "/opt/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/__w/field-service/field-service/fieldservice_account_analytic/models/account_move.py", line 22, in create
    raise ValidationError(
odoo.exceptions.ValidationError: No analytic account set on the order's Location.
```