[14.0][FIX]AttributeError: 'res.config.settings' object has no attribute 'group_manage_vendor_price'.
fieldservice 14.0.1.2.0

[UPD] Update fieldservice.pot

Update translation files

Updated by "Update PO files to match POT (msgmerge)" hook in Weblate.

Translation: field-service-14.0/field-service-14.0-fieldservice
Translate-URL: https://translation.odoo-community.org/projects/field-service-14-0/field-service-14-0-fieldservice/